# Promotion target for the dev stage. Kargo updates image.tag and env.LAMBDA_URL.
stage: dev
replicaCount: 1
image:
  tag: 3
env:
  LAMBDA_URL: https://xvk7cmevlit4zf4g4um5ew6wta0jxuqr.lambda-url.us-east-1.on.aws/
